unityStreamingAssets=.unity3d**STREAMING_ASSETS**
# org.gradle.jvmargs=-Xmx**JVM_HEAP_SIZE**M
org.gradle.jvmargs=-Xmx4g -Xss4m
org.gradle.parallel=true
android.enableR8=**MINIFY_WITH_R_EIGHT**
**ADDITIONAL_PROPERTIES**
android.suppressUnsupportedCompileSdk=34,35,36
android.enableJetifier=false
android.useAndroidX=true