namespace TWDModel
{
	public enum TWDModelResult
	{
		Queued = -2,
		Paused = -1,
		OK = 0,
		Error = 1,
		AlreadyUpgrading = 2,
		NotUpgrading = 3,
		AlreadyMaxLevel = 4,
		AlreadyMaxAmount = 5,
		AlreadyRemoving = 6,
		NotEnoughCurrency = 7,
		NotEnoughCapacity = 8,
		InvalidPosition = 9,
		Cancelled = 10,
		CampTypeNotFound = 11,
		Pending = 12,
		EquipmentNotFound = 13,
		NotEnoughSurvivors = 14,
		AlreadySearchingSurvivor = 15,
		CurrentlyNotSearchingSurvivors = 16,
		ModelObjectNotFound = 17,
		TimedActionAlreadyRunning = 18,
		TimedActionNotRunning = 19,
		SurvivorAlreadyInCollection = 20,
		SurvivorNotInCollection = 21,
		SurvivorNotAvailableForUnlocking = 22,
		InvalidBuildCreationRequested = 23,
		NoAvailableSlotsForNewSurvivor = 24,
		ModelListMismatch = 25,
		CombatOccupancyMismatch = 26,
		PlayerRandomMismatch = 27,
		NoGuildGiftsAvailable = 28,
		GuildAdStillRunning = 29,
		PhoneCallDefinitionNotFound = 30,
		Wrong = 31,
		DiamondExchangeDesync = 32,
		ChallengeMismatch = 33,
		MemberNotFound = 34,
		PlayerNameChangingNotAllowed = 35,
		GuildBattleMismatch = 36,
		Skip = 37,
		ChallengeMasterMissionNotUnlocked = 38,
		NotEnoughEquipToken = 39,
		CustomBundleClosed = 40,
		CustomBundleError = 41,
		BuyWebshopAndTradefairBundleCommandSuc = 42,
		SupportTalentNodeNotFound = 60,
		SupportTalentNodeCanNotUpgrade = 61
	}
}
